[package]
name = "evo-codegen-rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib_entry.rs"

[dependencies]
evo-lexer = { path = "../evo-lexer" }
evo-lowering = { path = "../evo-lowering" }

[dev-dependencies]
evo-parser = { path = "../evo-parser" }

[lints]
workspace = true
