[package]
name = "evo-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "evo"
path = "src/main.rs"

[dependencies]
evo-codegen-rust = { path = "../evo-codegen-rust" }
evo-diagnostics = { path = "../evo-diagnostics" }
evo-lexer = { path = "../evo-lexer" }
evo-lowering = { path = "../evo-lowering" }
evo-parser = { path = "../evo-parser" }

[lints]
workspace = true
